# Makefile.Host
TOP = ../..
include $(TOP)/configure/CONFIG


INC += averageRecord.h

DBD += averageRecord.dbd

# Source files (for depends target):
LIBSRCS += averageRecord.c

# Link everything into a library:
LIBRARY_IOC = averageRecord

include $(TOP)/configure/RULES
